### ISSUE TITLE
The highest possible score is 9990

### ISSUE THREAD

**Issue by T0nedeaf** [UltraStar-Deluxe/USDX#844] opened 2024-05-14 15:10 UTC
When I hit and paint all the notes in the Easy mode, usually I get the score 9990 (in nine different songs) and only in one song (Libertango) I got 10000. Why is it so? Is it OK? It would be nice to have 10000 in all cases.
I varied the number of golden notes in the *.txt files from 0 to 10, but it didn't help.

I use the v2024.3.0 version of USDX and Windows 11, Home edition 23H2.

**Comment by basisbit** [comment] 2024-05-14 18:10
This is a known problem caused by USDX cutting off grading of notes which are at the ending of a sentence / line. When it switches to display the next line's notes, the audio of the last note of the previous line might not yet have arrive and be graded yet because of the delay of the audio input + output devices. This was resolved in UltraStar Play / Melody Mania by separating the grading from the sentence displaying, but doing this in USDX would be quite a bit of work.

**Comment by T0nedeaf** [comment] 2024-05-15 01:24
Thank you.

**Comment by T0nedeaf** [comment] 2024-05-16 10:44
Nevertheless, USDX grades some songs correctly (I know 2 such songs (out of 11)). I tried to shorten the end notes of each line in the *txt files, but it didn't help. Can we fix the problem by changing something in a *.txt file?

**Comment by DeinAlptraum** [comment] 2024-10-03 15:33
@T0nedeaf do you have an example file where this happens so I can investigate this? I wasn't able to reproduce this

**Comment by T0nedeaf** [comment] 2024-10-04 05:08
Thank you. Here are examples of the songs for which you can get only 9990 point:
[Faul Wad Ad vs Pnau - Changes.txt](https://github.com/user-attachments/files/17253102/Faul.Wad.Ad.vs.Pnau.-.Changes.txt)
[Pink Floyd - Another Brick In The Wall (Part II).txt](https://github.com/user-attachments/files/17253176/Pink.Floyd.-.Another.Brick.In.The.Wall.Part.II.txt)
[Black Sabbath - Paranoid.txt](https://github.com/user-attachments/files/17253229/Black.Sabbath.-.Paranoid.txt)
[The White Stripes - Seven Nation Army.txt](https://github.com/user-attachments/files/17253232/The.White.Stripes.-.Seven.Nation.Army.txt)
[The Doors - Riders on the storm.txt](https://github.com/user-attachments/files/17253256/The.Doors.-.Riders.on.the.storm.txt)
[Nancy Sinatra - Bang Bang.txt](https://github.com/user-attachments/files/17253258/Nancy.Sinatra.-.Bang.Bang.txt)
[Marilyn Manson - Personal Jesus.txt](https://github.com/user-attachments/files/17253266/Marilyn.Manson.-.Personal.Jesus.txt)
[Scorpions - Dust In The Wind.txt](https://github.com/user-attachments/files/17253272/Scorpions.-.Dust.In.The.Wind.txt)
[Marilyn Manson - Sweet Dreams.txt](https://github.com/user-attachments/files/17253280/Marilyn.Manson.-.Sweet.Dreams.txt)
Unfortunately, I can't attach the MP3 files here. This file type is not supported.
You can download them from https://ultrastar-es.org/ or https://usdb.animux.de/
or I can send them to your email.

**Comment by T0nedeaf** [comment] 2024-10-04 10:14
> @T0nedeaf do you have an example file where this happens so I can investigate this? I wasn't able to reproduce this

And for the sake of comparison here are the songs for which you can get 10000 points.
[Grace Jones - I've seen that face before (Libertango).txt](https://github.com/user-attachments/files/17256708/Grace.Jones.-.I.ve.seen.that.face.before.Libertango.txt)
[Nick Cave & The Bad Seeds - Red right hand.txt](https://github.com/user-attachments/files/17256718/Nick.Cave.The.Bad.Seeds.-.Red.right.hand.txt)
[Marilyn Manson - Personal Jesus.txt](https://github.com/user-attachments/files/17256723/Marilyn.Manson.-.Personal.Jesus.txt)
[Depeche Mode - Personal Jesus.txt](https://github.com/user-attachments/files/17256724/Depeche.Mode.-.Personal.Jesus.txt)

**Comment by DeinAlptraum** [comment] 2024-10-04 20:40
Thank you for providing examples! Thanks to that, I think I was able to identify the issue.

**Comment by s09bQ5** [comment] 2024-10-08 07:00
My 2 cents on this issue:
 - @basisbit's concern that any change to the calculations makes USDX incompatible with existing high score lists is valid. This was brought up as well a few months ago when someone suggested to change the algorithm for detecting pitches.
 - Where does it say that the maximum for a song is always 10000? Do we have a special animation that happens only when 10000 is hit? If yes, can we maybe trigger that animation as well when the achievable maximum is lower and hit?
 - If you are able to hit 9990, you are playing in the wrong difficulty level. Nobody cares if a pro beats a beginner.

**Comment by DeinAlptraum** [comment] 2024-10-08 13:39
As far as I could tell, the maximum score is not communicated in-game anywhere, also no animation or similar as you described.

While this is not how I would want to play either, I don't think it is our place to question the playstyle of people who play on low difficulties and try to achieve a perfect score...

**Closed** 2024-10-08 22:00 UTC
