### ISSUE TITLE
[Possible bug]: Ini.Save;

### ISSUE THREAD

**Issue by djstkg** [UltraStar-Deluxe/USDX#552] opened 2020-10-13 11:45 UTC
**Please, do not create duplicate issues**

### Actual behaviour

    Ini.Save; in UMain.pas will be executed and overwrites the .ini even if the .ini exists.

### Expected behaviour

already configured .ini should not be overwritten. Unless explicitly needed.

### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. change .ini
2. start ultrastardx
3. check .ini

### Details

Provide some additional information:

- USDX version: 2020.04.0 release
- Operating System + version: Armbian, 20.08.9 Bionic

**Comment by s09bQ5** [comment] 2020-10-13 12:07
USDX will read the existing ini before it saves the new one. It will automatically change only those settings that make no sense on your system, like when the sound device listed in config.ini is no longer available.
So, yeah, overwriting the config.ini is correct behavior.

Or do you have problems to run it from a read-only filesystem?

**Comment by djstkg** [comment] 2020-10-13 18:31
> USDX will read the existing ini before it saves the new one. It will automatically change only those settings that make no sense on your system, like when the sound device listed in config.ini is no longer available.
> So, yeah, overwriting the config.ini is correct behavior.
> 
> Or do you have problems to run it from a read-only filesystem?

It actually overwrites to Borderless, eventhough I explicitly set something else in .ini, for testing purposes.

No issue with read-only, I actually set .ini to readonly so it does not overwrite the mentioned setting.

**Comment by basisbit** [comment] 2020-10-13 20:24
It only overwrites invalid configuration. Closing this issue because this is as designed. You can still continue discussing about it here.

**Closed by basisbit** 2020-10-13 20:24 UTC

**Comment by djstkg** [comment] 2020-10-13 20:55
> It only overwrites invalid configuration. Closing this issue because this is as designed. You can still continue discussing about it here.

What is invalid in setting in .ini Fullscreen or Window mode?
