### ISSUE TITLE
Preview does not start automatically in song screen

### ISSUE THREAD

**Issue by M-Jup** [UltraStar-Deluxe/USDX#130] opened 2016-09-15 11:24 UTC
1.3.2-beta: When starting USDX for the first time, preview does not start automatically in the song selection screen. If this is an intended change from 1.1, an option to change the behavior would be nice.

**Comment by RattleSN4K3** [comment] 2016-09-15 12:38
A comment about that _issue_:

#5
> basisbit: The sing -> song preview not playing at first time is a feature, not a bug in my opinion. If you still want preview for that song, just press right arror key and then left arrow key.

I personally consider it as inconsistent behaviour though. As this likely differs accross the community/all users, an option is actually really helpful (similar to other options like _Advanced options_).

**Comment by ePirat** [comment] 2017-02-26 16:45
I've created a feature request for such an option and will close this "bug" as it is intended behavior.

**Closed by ePirat** 2017-02-26 16:45 UTC
Labels: wontfix
