### ISSUE TITLE
[BUG] Editor: red highlighting in overview timeline sometimes stuck

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#182] opened 2016-12-04 13:29 UTC
I don't exactly know how I got there, but the red highlight marker in the overview timeline (directly above the lyrics) stayed on the very first line regardless of where I went in the song, e.g. Line 24/76 in the following screenshot.

<img width="1680" alt="bildschirmfoto 2016-12-04 um 12 40 52" src="https://cloud.githubusercontent.com/assets/1497707/20866457/fecfdb08-ba2d-11e6-9f82-b8c765eb517e.png">

**Comment by basisbit** [comment] 2016-12-20 14:50
can't reproduce this issue. most likely got fixed in the mean time with all these uncaught writing to arrays out of range issues being solved now.

**Closed** 2016-12-20 14:58 UTC
