### ISSUE TITLE
libavutil version not supported

### ISSUE THREAD

**Issue by Gitman666** [UltraStar-Deluxe/USDX#555] opened 2020-11-27 21:00 UTC
**Please, do not create duplicate issues**

### Actual behaviour

When building USDX I get the following message:

```
/home/user/USDX/src/lib/ffmpeg-4.0/avutil.pas(81,4) Error: User defined: Linked version of libavutil is not yet supported!
/home/user/USDX/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(119,44) Note: Values in enumeration types have to be ascending
/home/user/USDX/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(504,48) Note: Values in enumeration types have to be ascending
/home/user/USDX/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(533,49) Note: Values in enumeration types have to be ascending
/home/user/USDX/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(554,44) Note: Values in enumeration types have to be ascending
/home/user/USDX/src/lib/ffmpeg-4.0/avutil.pas(293,1) Fatal: There were 1 errors compiling module, stopping

```

### Expected behaviour

Successful build

### Steps to reproduce

Simply build USDX against the latest version of libavutil

### Details

Provide some additional information:

- USDX version: Version 2020.4.0 Stable
- Operating System + version: Ubuntu 20.10

ffmpeg Version:

```
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

**Comment by basisbit** [comment] 2020-11-28 00:47
duplicate of #538 and some other fmmpeg version related issues.

**Closed by basisbit** 2020-11-28 00:47 UTC
