### ISSUE TITLE
New Avatar Add-On for Ultrastar - 100 Pics

### ISSUE THREAD

**Issue by marwin89** [UltraStar-Deluxe/USDX#728] opened 2023-08-04 06:10 UTC
Dear Ultrastar Deluxe maintainers,
@barbeque-squared, @basisbit, @bohning,

I've updated my free avatar collection for vocaluxe and ultrastar - with 100 new pics. You can use it for ultrastar deluxe community as well. 

**Could you spread the word and place the link on your page? wiki? Forum? Gitter? Discord?**

[Download and more information](https://github.com/marwin89/Vocaluxe-Ultrastar-Profile-Add-On)

![Preview2](https://github.com/UltraStar-Deluxe/USDX/assets/63517874/6b8370d1-be36-4195-b50e-56bccfcf2296)

PLUS: it would be cool if you activate [GitHub Discussion](https://github.com/features/discussions) in the repository

Regards

**Comment by barbeque-squared** [comment] 2023-08-12 10:29
I think linking to some avatar collections from somewhere is a good idea. Since it's not really a core part of USDX itself, I think this would work best as a wiki page. Probably called "Customization" or something?

That wiki page would then be linked from the main Readme (probably a new section "Further documentation" replacing "Command-Line Parameters" and "Controls" because it's just a bunch of wiki links).

But yeah, I've seen enough people's setup to know that "replace avatars" is something a lot of people do. I'll whip up something later today.

**Comment by marwin89** [comment] 2023-08-12 13:23
A "Customization"-page in wiki is a good idea.
a linking makes sense, cause the collection has another license than usdx itself and there are many other singing games as well. I would be happy to update just one place for next versions of the collection.

**Comment by barbeque-squared** [comment] 2023-08-12 15:12
I've created a wiki page here: https://github.com/UltraStar-Deluxe/USDX/wiki/Customization
and opened a pull request so that it gets linked to from the readme. will merge in a few hours.

**Comment by barbeque-squared** [comment] 2023-08-12 17:06
PR is merged so I'm closing this.

Re: Github Discussions
I'm not against enabling them and see how they get used (worst case it's trash and we can just disable them again -- gotta try it to see if it's useful or not); the problem is that I _can't_ enable them.
I'll ask around a bit because this isn't the first time this has come up. In the meantime (for other people who also maintain avatars/themes and want them on that page, and there's no "Discussions" button visible at the top), making a github issue is fine.

**Closed by barbeque-squared** 2023-08-12 17:06 UTC
