### ISSUE TITLE
Lyric Font Color in Duet Mode is Hardcoded?

### ISSUE THREAD

**Issue by Gaia2500** [UltraStar-Deluxe/USDX#648] opened 2023-02-06 14:27 UTC
### Actual behaviour
The displayed Lyric Font Color in Duet Mode cant be changed

### Expected behaviour
Use the Font Color from "config.ini" (SingLineColor, ActualLineColor, NextLineColor) as it is used in normal songs

### Steps to reproduce
1. make changes in "config.ini" for the entries SingLineColor, ActualLineColor, NextLineColor 
2. Open the ultrastardx.exe
3. See changes in font color while singing normal songs
4. See noo changes in font color while singing duet songs

### Details
- USDX version: v2020.4.0-stable
- OS: Win10

**Comment by basisbit** [comment] 2023-02-06 16:52
The lyric font color for duet modes depend on the colors of player 1 and player 2. This is as intended, not a bug.

**Comment by Gaia2500** [comment] 2023-02-09 13:30
Fair enough, but that should only affect the color that is assigned to "SingLineColor" in the "config.ini". There is no reason to use hardcoded colors for "ActualLineColor" and "NextLineColor". I am creating a theme with a dark "[sing]textBar.png" and "[sing]textBarDuet". And with this issue there is no way to make lyrics well readable in duet mode.

**Dummy RGB Colors in normal Mode:**
![screenshot0008](https://user-images.githubusercontent.com/124585341/217825456-f1a93407-edb9-49f8-b51c-9103698a74f2.jpg)
**None of the same dummy RGB Colors not applied in normal Mode:**
![screenshot0009](https://user-images.githubusercontent.com/124585341/217825464-fc92f3e7-8f05-4eea-9345-8c838a5137ad.jpg)

**Comment by barbeque-squared** [comment] 2023-02-09 16:15
It's _likely_ that this has already been fixed (or at the very least, it shouldn't be doing what you're experiencing anymore) in #623.
For a temporary workaround (until a proper release is made) you could try the Outline font mode, from what I remember that is at least not completely broken in the last release.

**Comment by barbeque-squared** [comment] 2023-03-24 06:30
Forgot to close this issue when v2023.3.0 was released, but this should be fixed now. The prebuilt version can be downloaded from the [releases](https://github.com/UltraStar-Deluxe/USDX/releases) page.

@Gaia2500 the expected behaviour using the dummy RGB colors is:
- Green and Blue are also used in Duets (ActualLineColor and NextLineColor)
- Red will get replaced by the player colors for P1 and P2

**Closed by barbeque-squared** 2023-03-24 06:30 UTC
