### ISSUE TITLE
Video stutters in preview and play

### ISSUE THREAD

**Issue by carcinojen** [UltraStar-Deluxe/USDX#285] opened 2017-08-02 05:58 UTC
Certain videos stutter hard. Game play is not affected otherwise. Downloaded several codec packs but I haven't been able to stop it from happening.

This issue does NOT occur in version 1.1.

- USDX version: 1.3.5 Beta
- Operating System + version: Windows 7 Ultimate 64-bit SP1

Video (no sound): https://youtu.be/Wb-iUG-MJ2k

**Comment by s09bQ5** [comment] 2017-08-05 23:40
The video not just stutters. The frames are played in the wrong order. What type of file is that video?
We've had a problem like this before 490a7690ed6a38b3758fcaf84569ee8e39ffcfd8.

**Comment by carcinojen** [comment] 2017-08-06 03:00
It's an mp4. Note not all mp4's behave this way.

![mp4details](https://user-images.githubusercontent.com/18300802/29000169-d16b13f2-7a31-11e7-89ff-d85ffceb1c16.jpg)

**Comment by s09bQ5** [comment] 2017-08-06 11:39
If it is MP4, this is most likely already fixed by the aforementioned commit.
You don't happen to be able to build the current development version?

**Comment by s09bQ5** [comment] 2017-08-08 08:56
Please try v2017.8.0 release last night.

**Comment by carcinojen** [comment] 2017-08-09 03:25
Hi.

I downloaded and installed it but when I hit "Sing" the program crashes and I get this:

![crashzo](https://user-images.githubusercontent.com/18300802/29103922-8604e2c4-7c90-11e7-8cc8-777d2aad4568.jpg)

Error log:

`UltraStar Deluxe - www.usdx.eu V 2017.8.0 dev Build Error Log
Date: 8/8/2017 Time: 23:18:36
-------------------
STATUS: Load Language [Initialization]
STATUS: Loading Skin List [Initialization]
STATUS: Loading Theme List [Initialization]
STATUS: Searching for Theme : C:\Program Files (x86)\UltraStar Deluxe\themes\*.ini [Theme.LoadList]
STATUS: Found Theme: Deluxe.ini [Theme.LoadList]
STATUS: Found Theme: Modern.ini [Theme.LoadList]
STATUS: Website-Manager [Initialization]
STATUS: DataBase System [Initialization]
STATUS: Initializing database: "C:\Program Files (x86)\UltraStar Deluxe\Ultrastar.db" [TDataBaseSystem.Init]
STATUS: Load Ini [Initialization]
STATUS: GamePath : C:\Program Files (x86)\UltraStar Deluxe\ []
STATUS: Using config : C:\Program Files (x86)\UltraStar Deluxe\config.ini [Ini]
STATUS: Found Video Mode: 1920x1080 [Video]
STATUS: Found Video Mode: 1680x1050 [Video]
STATUS: Found Video Mode: 1600x900 [Video]
STATUS: Found Video Mode: 1440x900 [Video]
STATUS: Found Video Mode: 1366x768 [Video]
STATUS: Found Video Mode: 1360x1024 [Video]
STATUS: Found Video Mode: 1360x768 [Video]
STATUS: Found Video Mode: 1280x1024 [Video]
STATUS: Found Video Mode: 1280x960 [Video]
STATUS: Found Video Mode: 1280x800 [Video]
STATUS: Found Video Mode: 1280x768 [Video]
STATUS: Found Video Mode: 1280x720 [Video]
STATUS: Found Video Mode: 1024x768 [Video]
STATUS: Found Video Mode: 800x600 [Video]
STATUS: Found Video Mode: 640x480 [Video]
STATUS: Found resolutions: 15 [Video]
STATUS: Write Ini [Initialization]
STATUS: Loading: C:\Program Files (x86)\UltraStar Deluxe\themes\Deluxe.ini [TTheme.LoadTheme]
ERROR:  no texture type for LoadingStaticAnimation found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic2Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic3Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic4Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic5Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic6Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SongRouletteStaticCat found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxStaticActualSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongMenuTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressSong found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressWeb found. [TTheme.ThemeLoadStatic]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Common start.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Common back.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\menu swoosh.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\select music change music 50.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\option change col.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\rimshot022b.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Applause.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\background track.mp3" [TAudioPlaybackBase.OpenDecodeStream]
STATUS: SDL_Init [UGraphic.Initialize3D]
STATUS: Use config resolution [SDL_SetVideoMode]
STATUS: Creating window [SDL_SetVideoMode]
STATUS: Set Video Mode...   Borderless fullscreen [SDL_SetVideoMode]
INFO:   OpenGL vendor ATI Technologies Inc. [UGraphic.InitializeScreen]
INFO:   OpenGL renderer AMD Radeon (TM) R7 300 Series [UGraphic.InitializeScreen]
INFO:   OpenGL version 4.5.13393 Compatibility Profile Context 15.200.0.0 [UGraphic.InitializeScreen]
INFO:   OpenGL vendor ATI Technologies Inc. [TTextureUnit.Create]
INFO:   OpenGL renderer AMD Radeon (TM) R7 300 Series [TTextureUnit.Create]
INFO:   OpenGL version 4.5.13393 Compatibility Profile Context 15.200.0.0 [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: -1 [TTextureUnit.Create]
STATUS: TDisplay.Create [UGraphic.Initialize3D]
STATUS: Loading Font Textures [UGraphic.Initialize3D]
STATUS: Building Fonts [LoadTextures]
STATUS: Loading Loading Screen [UGraphic.Initialize3D]
STATUS: Loading and checking songs [UGraphic.Initialize3D]
STATUS: Creating Category Covers Array [Initialization]
STATUS: Creating Avatars Cache [Initialization]
STATUS: Creating Song Array [Initialization]
STATUS: Searching For Songs [SongList]
STATUS: Search Complete [SongList]
STATUS: Creating 2nd Song Array [Initialization]
STATUS:  Loading Textures [UGraphic.Initialize3D]
STATUS: Loading Textures [LoadTextures]
STATUS: Loading Textures - A [LoadTextures]
STATUS: Loading Textures - B [LoadTextures]
STATUS: Loading Textures - C [LoadTextures]
STATUS: Loading Textures - Done [LoadTextures]
STATUS:  Loading Screens [UGraphic.Initialize3D]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
STATUS: Finish [Initialize3D]
STATUS: Playlist Manager [Initialization]
STATUS: Effect Manager [Initialization]
STATUS:   # Name                           Version  Status     Paused  #Errors [LuaCore Plugins]
STATUS:   0 party mode: 1000blind          1.00     running    False   0      [LuaCore Plugins]
STATUS:   1 party mode: 2000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:   2 party mode: 2000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   3 party mode: 5000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:   4 party mode: 5000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   5 party mode: 500blind           1.00     running    False   0      [LuaCore Plugins]
STATUS:   6 party mode: 7000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:   7 party mode: 5000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   8 party mode: blindLyrics        1.00     running    False   0      [LuaCore Plugins]
STATUS:   9 party mode: blindTotal         1.00     running    False   0      [LuaCore Plugins]
STATUS:  10 party mode: blind              1.00     running    False   0      [LuaCore Plugins]
STATUS:  11 party mode: deaf               1.00     running    False   0      [LuaCore Plugins]
STATUS:  12 party mode: duel               1.00     running    False   0      [LuaCore Plugins]
STATUS:  13 party mode: hardcore           1.00     running    False   0      [LuaCore Plugins]
STATUS:  14 party mode: holdtheline        0.6      running    False   0      [LuaCore Plugins]
STATUS:  15 party mode: holdthelineblind   0.6      running    False   0      [LuaCore Plugins]
STATUS:  16 party mode: shortsong          1.00     running    False   0      [LuaCore Plugins]
STATUS:  17 party mode: teamduel           1.00     running    False   0      [LuaCore Plugins]
STATUS: Main Loop [Initialization]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
ERROR:  BASS_RecordStart: Sample-Format not supported [TBassInputDevice.Open]
`

**Comment by basisbit** [comment] 2017-08-09 17:38
@carcinojen please open a new issue report for this.

**Comment by carcinojen** [comment] 2017-08-09 20:32
Deleting config.ini + .db files worked. Also the video playback is perfect. Should I still open a new issue report for the crash?

Thanks!

**Comment by basisbit** [comment] 2017-08-09 21:00
nah, I already know what the problem is and will fix it within the next weeks some time. Thanks a lot for your feedback! Also, please enjoy playing lots of karaoke! 😄

**Closed by basisbit** 2017-08-09 21:00 UTC
