### ISSUE TITLE
Create a new USDX release

### ISSUE THREAD

**Issue by cRaZy-bisCuiTs** [UltraStar-Deluxe/USDX#625] opened 2022-11-22 16:07 UTC
### Actual behaviour
The current stable version "v2020.4.0" is from Apr 30, 2020 - pretty old. 

### Solution
Please provide a new stable version. For distros with USDX packaging having a new official release would be appreciated.

**Comment by basisbit** [comment] 2022-11-26 15:54
sounds like a good idea! How about targeting end of the year to finish the leftover PRs and test a new version?
@bohning @barbeque-squared @s09bQ5 Would you be up for that?

**Comment by bohning** [comment] 2022-11-26 15:58
> sounds like a good idea! How about targeting end of the year to finish the leftover PRs and test a new version? @bohning @barbeque-squared @s09bQ5 Would you be up for that?

Would be very up for that!

**Comment by s09bQ5** [comment] 2022-11-26 16:17
yes!

**Comment by barbeque-squared** [comment] 2022-11-27 14:42
> sounds like a good idea! How about targeting end of the year to finish the leftover PRs and test a new version? Would you be up for that?

If the test window is large enough (ie at least a week) I can do some testing.
Regarding my own PR's, #618 (already finished) and #628 (I'll update it later this week) are the ones that I'm going to give priority in this, some of the other ones (refactorings etc) are probably better off being in master for a longer time.

**Comment by cRaZy-bisCuiTs** [comment] 2022-11-28 23:03
Thank you very much guys! You're amazing! I really do appreciate your engagement. We had a lot of amazing karaoke evenings within the last two decades. :)

**Comment by josch88** [comment] 2022-12-27 10:30
Hi guys, any news about a new release?
I can support testing if you want.

**Comment by basisbit** [comment] 2022-12-27 11:20
There are still a couple of open pull requests to be reviewed by anyone who has spare time and motivation for it. Besides that, there are a couple open pull requests that are marked as testers-needed. Those need someone to test the change to verify that the pull request doesn't break related stuff / corner cases and works on the usual operating systems.

**Comment by barbeque-squared** [comment] 2023-01-16 13:05
What kind of artifacts should be included in every release? The Releases page differ a bit per release. Please also specify where they are coming from -- for example, I have no idea where the Mac packages are from.

**Comment by s09bQ5** [comment] 2023-01-16 15:24
The AppImage built by AppVeyor in the "Ubuntu" job.

https://github.com/AppImage/appimage.github.io/blob/master/README.md says
> Ideally, the file in data/ contains a link to https://github.com/User/App/ (not to a specific AppImage!), and if the AppImage follows the standard nomenclature, then https://github.com/User/App/releases/whatever/App-1.0-x86_64.AppImage, https://github.com/User/App/releases/whatever/App-1.1-x86_64.AppImage,... will automatically be picked up.

No need to have a Flatpak artifact. Once we have a stable release, we can make Flathub build and host the released version.

Btw., did both the AppImage and Flatpak 32 bit build fail on AppVeyor or was it just the Flatpak build that led to b7f4de652e991b6c6c9a7d0b342147afc03998ae? I'd really like to see a 32 bit AppImage in the release artifacts. According to flathub/flathub#3193 the issue we saw with the 32 bit Flatpak build are temporary.

**Comment by s09bQ5** [comment] 2023-01-16 16:00
Ugh, something is fishy with the SDL build inside the AppImage. It doesn't even attempt to use ALSA and then fails to use ALSA's /dev/dsp emulation.

How many days do I have to fix that?

**Comment by barbeque-squared** [comment] 2023-01-17 09:15
@s09bQ5 I wasn't going to try and do a release yet. I want to add some basic logging like Portaudio now has to the other ones, have less duplication of the version number throughout the codebase, and figure out what builds we actually need (and how to make/test them).

I don't have a lot of time in January, so no need to rush it. My comment was really only about the latter point, the "figuring out" stage.

**Comment by s09bQ5** [comment] 2023-01-18 10:35
> Ugh, something is fishy with the SDL build inside the AppImage. It doesn't even attempt to use ALSA and then fails to use ALSA's /dev/dsp emulation.

Turns out this was due to old libraries on the system I used to test.
SDL >= 2.0.6 doesn't accept libasound older than 1.0.27 if it has been built with a libasound >= 1.0.27. 1.0.27 has been release in 2013.
SDL >= 2.0.16 triggers a bug in libXi 1.5 to 1.7.3 that leads to a frozen window on startup. 1.7.4 has been release in 2014.

I don't think anything needs to be done.

**Comment by barbeque-squared** [comment] 2023-02-28 16:03
Now that we're generating Windows zips+installers again, is there anything else that needs to be done for a release? On my Todo list I have:
- remove the release notes altogether from the readme (just link to the general releases page instead)
- go through all the commits since the last release and make a (draft) release page

and once that's done: actually do the release.

I want to stick to AppVeyor artifacts. I'm fine with whoever did Mac builds in the past adding them afterwards, but if they need to be there from the start I suggest a PR that makes AppVeyor build them instead.

It's been 3+ months since this issue was opened (and almost 3 _years_ since the last release), so I'll probably just go ahead and do it this weekend.

PS: FFmpeg 6.0 was _just_ released, but unless things go really fast I'll just release with support up to 5 initially. Future releases will be more frequent and with smaller changesets anyway.

**Comment by basisbit** [comment] 2023-02-28 16:16
Please first create a release candidate and have people test it for at least like 1 or 2 weeks.

**Comment by barbeque-squared** [comment] 2023-03-01 16:10
I've been running git versions for years, if there was anything newly broken I would have noticed by now. Me and some other people have also been playing around with the Windows installer and the game, we can't find any regressions.

For release notes I have this so far:
![2023-03-01-161458_692x663_scrot](https://user-images.githubusercontent.com/5775429/222191749-ec9974d1-ba50-4c73-b14a-46edc13735c7.png)

I didn't put _all_ of the things in there, because a lot of stuff just isn't relevant for end users. The features/enhancements/bug fixes sections are taken from how AxonFramework does their releases, because it works _really_ well.

Is there anything missing from them? Maintainers etc can edit directly, otherwise just comment here.

**Comment by brianch** [comment] 2023-03-01 22:31
I like basisbit suggestion about making a RC first (it would be nice to have people test it in different systems, and with other hardware).

Do you have any idea if ffmpeg 6 changed much of the api? Since it's already out, perhaps we could add support for it before making a release. I think I can help take a look (supposing the arch package won't take more than a few days to get released).

About the things that aren't very relevant to end users, perhaps you could add a section "Internal changes" or something like that, just to show the work that has been done. (the auto generation of the appImage and Flatpaks could go there too).

**Comment by s09bQ5** [comment] 2023-03-02 07:01
None of the functions we use vanished with FFmpeg 6.0. `AVCodec`, `AVCodecContext`, and `AVStream` changed their layout. `AVCodec` lost its `flush` element. `AVCodecContext` lost its `debug_mv` element. I haven't checked the constants yet, but I doubt there are any changes.

Places where we access `debug_mv` can simply be $if'ed out. That element didn't have any effect since 2017 and we set it to 0 anyway (i.e. no motion vector debugging).

For `flush` see #259.

**Comment by barbeque-squared** [comment] 2023-03-02 07:04
@brianch

re: RC
I consider any CI job to be a release candidate. It can already be tested. It's just that nobody volunteers for it. And there will always be bugs; I'd rather get into a habit of people not having to wait another three years before their bug is (maybe) fixed. Plus: if a new version did introduce an actual new bug, people only have to go back one or two versions as a temporary workaround, and not have to miss out on all the other improvements.
(the 2017 and 2020 versions also have bugs, and at least one of them had lengthy release candidates, so I also don't see the actually added value here. I have enough experience with both the 'once-in-a-blue-moon' releases and regular releases to say that I vastly prefer the latter)

re: ffmpeg 6
I thought I saw an issue about that yesterday (I really liked how it approached the issue: first change something in the way something's done for the currently already supported versions, then adding 6 becomes trivial) but I don't know where it has gone.
But see also my point about RC's. There will _always_ be some new feature/bug that would be 'absolutely necessary' for the next release.

re: internal changes
I like this. Will add it later today.

**Comment by barbeque-squared** [comment] 2023-03-03 18:46
Did not get around to it yesterday.
![2023-03-03-191653_715x701_scrot](https://user-images.githubusercontent.com/5775429/222797201-ed656f3c-9454-4857-8f3d-000409197431.png)
Decided to put some related issues together (the Enhancements/Video performance ones, and then the one simply called "Various fixes") to make the list less daunting.

I think from the git history some commits were done directly on master, I did not mention these (they mostly fall under the "Various fixes"), but let me know if I missed something noteworthy or something is wrong.

Unless any major issues (that weren't already there in 2020.4.0) are reported in the current CI artifacts, I'll merge in #653 tomorrow as the final one and then do the thing.

**Comment by brianch** [comment] 2023-03-03 23:17
The draft looks good.

But I still think that, especially now that @s09bQ5 did all the work already, there's no reason to not wait a little bit for their ffmpeg related PRs to be reviewed.

**Comment by barbeque-squared** [comment] 2023-03-04 14:24
The ffmpeg stuff (along with some other minor last-minute things) is in. They don't break anything current, worst case there's still some bug in ffmpeg 6 but ffmpeg 6 for some users is still better than ffmpeg 6 for nobody.

I'm going to add these last items to the release notes, wait for the CI to catch up, do some final final tests and then do the release commit (and then more waiting for the CI before it'll actually be live).

**Comment by barbeque-squared** [comment] 2023-03-05 12:36
The release is out, see the releases page: https://github.com/UltraStar-Deluxe/USDX/releases
There's no apple build this time (it doesn't get autogenerated) but until that's in place, someone who can actually build for apple can add it I guess.

**Closed by barbeque-squared** 2023-03-05 12:36 UTC

**Comment by bohning** [comment] 2023-03-05 13:07
> The release is out, see the releases page: https://github.com/UltraStar-Deluxe/USDX/releases There's no apple build this time (it doesn't get autogenerated) but until that's in place, someone who can actually build for apple can add it I guess.

I added the freshly built Mac dmg. I’m on a 2015 Macbook Pro running macOS Monterey 12.6.3.

**Comment by s09bQ5** [comment] 2023-03-05 14:17
I'll try to slightly change the names of the AppImages (drop commit id, replace dot with hyphen) to allow the AppImage store to pick them up automatically from the Github Releases page.

**Comment by s09bQ5** [comment] 2023-03-06 11:48
AppImage/appimage.github.io#3116
flathub/flathub#3959
