### ISSUE TITLE
Graphics/sprites not showing on one of my macs

### ISSUE THREAD

**Issue by motin** [UltraStar-Deluxe/USDX#255] opened 2017-02-27 11:27 UTC
The game launches on both my macs, but on one of the macs, the graphics are screwed up, the buttons have no backgrounds and the mousepointer is a square, no album covers or other imagery shows etc.

Both run the latest Mac OS X Sierra (10.12.3), so I am not sure as to why it is not working on one of the macs. 

### Steps to reproduce

1. Download the OSX build from https://github.com/UltraStar-Deluxe/USDX/issues/204#issuecomment-282557990
2. Launch the game

### Details

Provide some additional information:

- USDX version: 1_3_5_2017-02-15.dmg
- Operating System + version: Mac OS X Sierra (10.12.3)

**Comment by basisbit** [comment] 2017-02-27 11:43
could you please provide the Error.log file (especially the OpenGL parts)?

**Comment by motin** [comment] 2017-02-27 11:53
Sure, but there is no error log file in ~/Library/Application Support/UltraStarDeluxe1.3 - where should it be?

**Comment by basisbit** [comment] 2017-02-27 12:34
@kamischi @bohning @ePirat anyone of you know where the Error.log file should be found on macOS?

**Comment by kamischi** [comment] 2017-02-27 12:48
~/Library/Logs/UltraStar\ Deluxe/Error.log

**Comment by motin** [comment] 2017-02-27 13:11
Thanks @kamischi, here is the Error.log http://pastebin.ca/3772929

**Comment by motin** [comment] 2017-02-27 13:15
And a screenshot of how it looks like: <img width="1440" alt="screen shot 2017-02-27 at 14 14 24" src="https://cloud.githubusercontent.com/assets/793037/23362674/1fd9591c-fcf7-11e6-9624-f9c9c2f64d7e.png">

**Comment by basisbit** [comment] 2017-02-27 14:12
could you check if there are jpg image files in the folder  /Users/motin/Library/Application Support/UltraStarDeluxe1.3/themes/Modern/ ?

**Comment by motin** [comment] 2017-02-27 14:19
```
$ ls -l "/Users/motin/Library/Application Support/UltraStarDeluxe1.3/themes/Modern/"
total 11648
-rw-r--r--  1 motin  staff    10107 Feb 27 14:13 Blue.ini
-rw-r--r--  1 motin  staff    10125 Feb 27 14:13 Winter.ini
-rw-r--r--  1 motin  staff   106213 Feb 27 14:13 [bg-load]blue.jpg
-rw-r--r--  1 motin  staff   471938 Feb 27 14:13 [bg-load]fall.jpg
-rw-r--r--  1 motin  staff   381304 Feb 27 14:13 [bg-load]summer.jpg
-rw-r--r--  1 motin  staff   243663 Feb 27 14:13 [bg-load]winter.jpg
-rw-r--r--  1 motin  staff    89719 Feb 27 14:13 [bg-main]blue.jpg
-rw-r--r--  1 motin  staff   392979 Feb 27 14:13 [bg-main]fall.jpg
-rw-r--r--  1 motin  staff   447517 Feb 27 14:13 [bg-main]summer.jpg
-rw-r--r--  1 motin  staff   268024 Feb 27 14:13 [bg-main]winter.jpg
-rw-r--r--  1 motin  staff  2118942 Feb 27 14:13 [bg-video]ribbon.mov
-rw-r--r--  1 motin  staff     1546 Feb 27 14:13 [button]13.png
-rw-r--r--  1 motin  staff     1513 Feb 27 14:13 [button]alt.png
-rw-r--r--  1 motin  staff     1496 Feb 27 14:13 [button]az.png
-rw-r--r--  1 motin  staff     3964 Feb 27 14:13 [button]c.png
-rw-r--r--  1 motin  staff     4096 Feb 27 14:13 [button]del.png
-rw-r--r--  1 motin  staff     2176 Feb 27 14:13 [button]enter.png
-rw-r--r--  1 motin  staff     1508 Feb 27 14:13 [button]esc.png
-rw-r--r--  1 motin  staff     4102 Feb 27 14:13 [button]ins.png
-rw-r--r--  1 motin  staff     1225 Feb 27 14:13 [button]j.png
-rw-r--r--  1 motin  staff     1256 Feb 27 14:13 [button]m.png
-rw-r--r--  1 motin  staff     4072 Feb 27 14:13 [button]navi.png
-rw-r--r--  1 motin  staff     1231 Feb 27 14:13 [button]p.png
-rw-r--r--  1 motin  staff      109 Feb 27 14:13 [color]black-fade.png
-rw-r--r--  1 motin  staff      238 Feb 27 14:13 [color]hue-bar.png
-rw-r--r--  1 motin  staff     3621 Feb 27 14:13 [color]picker.jpg
-rw-r--r--  1 motin  staff     4531 Feb 27 14:13 [color]picker.png
-rw-r--r--  1 motin  staff    92106 Feb 27 14:13 [color]pickerbg.png
-rw-r--r--  1 motin  staff      362 Feb 27 14:13 [color]pointer.png
-rw-r--r--  1 motin  staff       75 Feb 27 14:13 [color]white-fade.png
-rw-r--r--  1 motin  staff     4231 Feb 27 14:13 [editsub]freestyle.png
-rw-r--r--  1 motin  staff     4325 Feb 27 14:13 [editsub]gold.png
-rw-r--r--  1 motin  staff     4261 Feb 27 14:13 [editsub]next-seq.png
-rw-r--r--  1 motin  staff     4297 Feb 27 14:13 [editsub]play-note.png
-rw-r--r--  1 motin  staff     4362 Feb 27 14:13 [editsub]play-with-note.png
-rw-r--r--  1 motin  staff     4263 Feb 27 14:13 [editsub]play.png
-rw-r--r--  1 motin  staff     4270 Feb 27 14:13 [editsub]previous-seq.png
-rw-r--r--  1 motin  staff     4326 Feb 27 14:13 [editsub]undo.png
-rw-r--r--  1 motin  staff    24444 Feb 27 14:13 [effect]goldenNoteStar.png
-rw-r--r--  1 motin  staff    40783 Feb 27 14:13 [effect]perfectNoteStar.png
-rw-r--r--  1 motin  staff      337 Feb 27 14:13 [helper]buttonFade.png
-rw-r--r--  1 motin  staff     7193 Feb 27 14:13 [helper]rectangle.jpg
-rw-r--r--  1 motin  staff      777 Feb 27 14:13 [icon]cd.png
-rw-r--r--  1 motin  staff      694 Feb 27 14:13 [icon]error.png
-rw-r--r--  1 motin  staff      803 Feb 27 14:13 [icon]main.png
-rw-r--r--  1 motin  staff      954 Feb 27 14:13 [icon]options.png
-rw-r--r--  1 motin  staff      694 Feb 27 14:13 [icon]party.png
-rw-r--r--  1 motin  staff      747 Feb 27 14:13 [icon]question.png
-rw-r--r--  1 motin  staff      794 Feb 27 14:13 [icon]score.png
-rw-r--r--  1 motin  staff      379 Feb 27 14:13 [icon]song_calcmedley.png
-rw-r--r--  1 motin  staff     3826 Feb 27 14:13 [icon]song_duet.png
-rw-r--r--  1 motin  staff      384 Feb 27 14:13 [icon]song_medley.png
-rw-r--r--  1 motin  staff      724 Feb 27 14:13 [icon]song_menu.png
-rw-r--r--  1 motin  staff     3301 Feb 27 14:13 [icon]song_rap.png
-rw-r--r--  1 motin  staff      960 Feb 27 14:13 [icon]song_search.png
-rw-r--r--  1 motin  staff      629 Feb 27 14:13 [icon]song_video.png
-rw-r--r--  1 motin  staff      676 Feb 27 14:13 [icon]stats.png
-rw-r--r--  1 motin  staff     3002 Feb 27 14:13 [icon]video.png
-rw-r--r--  1 motin  staff     5635 Feb 27 14:13 [interface]cursor.png
-rw-r--r--  1 motin  staff     4086 Feb 27 14:13 [interface]cursor_pressed.png
-rw-r--r--  1 motin  staff     4063 Feb 27 14:13 [interface]dialog_background.png
-rw-r--r--  1 motin  staff     7957 Feb 27 14:13 [interface]dialog_background2.png
-rw-r--r--  1 motin  staff     9460 Feb 27 14:13 [interface]dialog_backgroundtop.png
-rw-r--r--  1 motin  staff    47850 Feb 27 14:13 [interface]dialog_backgroundtop2.png
-rw-r--r--  1 motin  staff      485 Feb 27 14:13 [interface]select_arrow_left.png
-rw-r--r--  1 motin  staff      485 Feb 27 14:13 [interface]select_arrow_right.png
-rw-r--r--  1 motin  staff      477 Feb 27 14:13 [interface]selectbg_search.png
-rw-r--r--  1 motin  staff     3146 Feb 27 14:13 [jukebox]close.png
-rw-r--r--  1 motin  staff     1343 Feb 27 14:13 [jukebox]currentsong.png
-rw-r--r--  1 motin  staff     3332 Feb 27 14:13 [jukebox]lyric.png
-rw-r--r--  1 motin  staff     3941 Feb 27 14:13 [jukebox]options.png
-rw-r--r--  1 motin  staff     3203 Feb 27 14:13 [jukebox]pin.png
-rw-r--r--  1 motin  staff     3556 Feb 27 14:13 [jukebox]random.png
-rw-r--r--  1 motin  staff     3409 Feb 27 14:13 [jukebox]repeat.png
-rw-r--r--  1 motin  staff    12014 Feb 27 14:13 [jukebox]songlist.png
-rw-r--r--  1 motin  staff     3083 Feb 27 14:13 [jukebox]songlistdown.png
-rw-r--r--  1 motin  staff     3073 Feb 27 14:13 [jukebox]songlistup.png
-rw-r--r--  1 motin  staff     3329 Feb 27 14:13 [jukebox]songmenunext.png
-rw-r--r--  1 motin  staff     3315 Feb 27 14:13 [jukebox]songmenuplaylist.png
-rw-r--r--  1 motin  staff     3388 Feb 27 14:13 [jukebox]songmenuplaypause.png
-rw-r--r--  1 motin  staff     3309 Feb 27 14:13 [jukebox]songmenuprevious.png
-rw-r--r--  1 motin  staff    15177 Feb 27 14:13 [jukebox]songoptions.png
-rw-r--r--  1 motin  staff      317 Feb 27 14:13 [jukebox]timeBar.jpg
-rw-r--r--  1 motin  staff     3075 Feb 27 14:13 [jukebox]timeBarBG.png
-rw-r--r--  1 motin  staff     3217 Feb 27 14:13 [jukebox]timeBarSongMenuBG.png
-rw-r--r--  1 motin  staff     1124 Feb 27 14:13 [jukebox]title.png
-rw-r--r--  1 motin  staff      232 Feb 27 14:13 [main]button.png
-rw-r--r--  1 motin  staff     4761 Feb 27 14:13 [main]buttonf.jpg
-rw-r--r--  1 motin  staff      271 Feb 27 14:13 [main]mainBar.png
-rw-r--r--  1 motin  staff     2267 Feb 27 14:13 [main]playerNumberBox.png
-rw-r--r--  1 motin  staff      673 Feb 27 14:13 [main]selectbg.png
-rw-r--r--  1 motin  staff    15045 Feb 27 14:13 [main]songCover.jpg
-rw-r--r--  1 motin  staff     1097 Feb 27 14:13 [main]songSelection1.png
-rw-r--r--  1 motin  staff      523 Feb 27 14:13 [main]songSelection2.png
-rw-r--r--  1 motin  staff     3510 Feb 27 14:13 [main]songSelection3.png
-rw-r--r--  1 motin  staff     2893 Feb 27 14:13 [main]songSelection4.png
-rw-r--r--  1 motin  staff     2891 Feb 27 14:13 [main]songSelection5.png
-rw-r--r--  1 motin  staff      912 Feb 27 14:13 [menu]PopUpFg.png
-rw-r--r--  1 motin  staff    18921 Feb 27 14:13 [menu]jumpToBg.png
-rw-r--r--  1 motin  staff    18529 Feb 27 14:13 [menu]songMenuBg.png
-rw-r--r--  1 motin  staff     4707 Feb 27 14:13 [menu]songMenuSelectBg.png
-rw-r--r--  1 motin  staff     3792 Feb 27 14:13 [name]frame.png
-rw-r--r--  1 motin  staff     4162 Feb 27 14:13 [name]noavatarP1.png
-rw-r--r--  1 motin  staff     4725 Feb 27 14:13 [name]noavatarP10.png
-rw-r--r--  1 motin  staff     4725 Feb 27 14:13 [name]noavatarP11.png
-rw-r--r--  1 motin  staff     4725 Feb 27 14:13 [name]noavatarP12.png
-rw-r--r--  1 motin  staff     4217 Feb 27 14:13 [name]noavatarP2.png
-rw-r--r--  1 motin  staff     4236 Feb 27 14:13 [name]noavatarP3.png
-rw-r--r--  1 motin  staff     4211 Feb 27 14:13 [name]noavatarP4.png
-rw-r--r--  1 motin  staff     4199 Feb 27 14:13 [name]noavatarP5.png
-rw-r--r--  1 motin  staff     4247 Feb 27 14:13 [name]noavatarP6.png
-rw-r--r--  1 motin  staff     4725 Feb 27 14:13 [name]noavatarP7.png
-rw-r--r--  1 motin  staff     4725 Feb 27 14:13 [name]noavatarP8.png
-rw-r--r--  1 motin  staff     4725 Feb 27 14:13 [name]noavatarP9.png
-rw-r--r--  1 motin  staff     3136 Feb 27 14:13 [name]player.png
-rw-r--r--  1 motin  staff     3126 Feb 27 14:13 [name]select.png
-rw-r--r--  1 motin  staff    10954 Feb 27 14:13 [party]Joker.png
-rw-r--r--  1 motin  staff      293 Feb 27 14:13 [party]playerButton.png
-rw-r--r--  1 motin  staff     3370 Feb 27 14:13 [party]playerTeamButton.png
-rw-r--r--  1 motin  staff     2904 Feb 27 14:13 [party]playerselectbg.png
-rw-r--r--  1 motin  staff      362 Feb 27 14:13 [party]pointer.png
-rw-r--r--  1 motin  staff      358 Feb 27 14:13 [party]roundBG1.png
-rw-r--r--  1 motin  staff      279 Feb 27 14:13 [party]roundBG2.png
-rw-r--r--  1 motin  staff      407 Feb 27 14:13 [party]roundBG3.png
-rw-r--r--  1 motin  staff      365 Feb 27 14:13 [party]roundBG4.png
-rw-r--r--  1 motin  staff     3453 Feb 27 14:13 [party]roundTeamButton.png
-rw-r--r--  1 motin  staff      642 Feb 27 14:13 [party]scoreBG1.png
-rw-r--r--  1 motin  staff      314 Feb 27 14:13 [party]scoreBG2.png
-rw-r--r--  1 motin  staff    11833 Feb 27 14:13 [party]scoreDecoration.png
-rw-r--r--  1 motin  staff     3871 Feb 27 14:13 [party]teamPoints.png
-rw-r--r--  1 motin  staff     7032 Feb 27 14:13 [party]winDecoration.png
-rw-r--r--  1 motin  staff     3923 Feb 27 14:13 [party]winTeamButton1.png
-rw-r--r--  1 motin  staff     3595 Feb 27 14:13 [party]winTeamButton2.png
-rw-r--r--  1 motin  staff     3514 Feb 27 14:13 [party]winTeamButton3.png
-rw-r--r--  1 motin  staff      371 Feb 27 14:13 [rap]notesBgLeft.png
-rw-r--r--  1 motin  staff      200 Feb 27 14:13 [rap]notesBgMid.png
-rw-r--r--  1 motin  staff      341 Feb 27 14:13 [rap]notesBgRight.png
-rw-r--r--  1 motin  staff      620 Feb 27 14:13 [rap]notesLeft.png
-rw-r--r--  1 motin  staff      281 Feb 27 14:13 [rap]notesMid.png
-rw-r--r--  1 motin  staff      673 Feb 27 14:13 [rap]notesPlainLeft.png
-rw-r--r--  1 motin  staff      299 Feb 27 14:13 [rap]notesPlainMid.png
-rw-r--r--  1 motin  staff      671 Feb 27 14:13 [rap]notesPlainRight.png
-rw-r--r--  1 motin  staff      594 Feb 27 14:13 [rap]notesRightrap.png
-rw-r--r--  1 motin  staff     2825 Feb 27 14:13 [score]Line.png
-rw-r--r--  1 motin  staff      496 Feb 27 14:13 [score]bar_box_dark.png
-rw-r--r--  1 motin  staff      490 Feb 27 14:13 [score]bar_box_light.png
-rw-r--r--  1 motin  staff      484 Feb 27 14:13 [score]bar_box_lightest.png
-rw-r--r--  1 motin  staff      307 Feb 27 14:13 [score]box.png
-rw-r--r--  1 motin  staff     3231 Feb 27 14:13 [score]buttonsendscore.png
-rw-r--r--  1 motin  staff     2275 Feb 27 14:13 [score]endcap.png
-rw-r--r--  1 motin  staff     3183 Feb 27 14:13 [score]frame.png
-rw-r--r--  1 motin  staff     3581 Feb 27 14:13 [score]glass_box.png
-rw-r--r--  1 motin  staff      266 Feb 27 14:13 [score]level.png
-rw-r--r--  1 motin  staff      524 Feb 27 14:13 [score]levelRound.png
-rw-r--r--  1 motin  staff      213 Feb 27 14:13 [score]level_dark.png
-rw-r--r--  1 motin  staff      410 Feb 27 14:13 [score]level_dark_round.png
-rw-r--r--  1 motin  staff      209 Feb 27 14:13 [score]level_light.png
-rw-r--r--  1 motin  staff      445 Feb 27 14:13 [score]level_light_round.png
-rw-r--r--  1 motin  staff      209 Feb 27 14:13 [score]level_lightest.png
-rw-r--r--  1 motin  staff      467 Feb 27 14:13 [score]level_lightest_round.png
-rw-r--r--  1 motin  staff     7412 Feb 27 14:13 [score]rating_0.png
-rw-r--r--  1 motin  staff     8206 Feb 27 14:13 [score]rating_1.png
-rw-r--r--  1 motin  staff     9681 Feb 27 14:13 [score]rating_2.png
-rw-r--r--  1 motin  staff     8363 Feb 27 14:13 [score]rating_3.png
-rw-r--r--  1 motin  staff     8231 Feb 27 14:13 [score]rating_4.png
-rw-r--r--  1 motin  staff     8720 Feb 27 14:13 [score]rating_5.png
-rw-r--r--  1 motin  staff     8162 Feb 27 14:13 [score]rating_6.png
-rw-r--r--  1 motin  staff     9573 Feb 27 14:13 [score]rating_7.png
-rw-r--r--  1 motin  staff      884 Feb 27 14:13 [sing.player1]lyric_active.png
-rw-r--r--  1 motin  staff      862 Feb 27 14:13 [sing.player1]lyric_inactive.png
-rw-r--r--  1 motin  staff     1034 Feb 27 14:13 [sing.player2]lyric_active.png
-rw-r--r--  1 motin  staff      948 Feb 27 14:13 [sing.player2]lyric_inactive.png
-rw-r--r--  1 motin  staff      988 Feb 27 14:13 [sing.player3]lyric_active.png
-rw-r--r--  1 motin  staff      911 Feb 27 14:13 [sing.player3]lyric_inactive.png
-rw-r--r--  1 motin  staff      966 Feb 27 14:13 [sing.player4]lyric_active.png
-rw-r--r--  1 motin  staff      861 Feb 27 14:13 [sing.player4]lyric_inactive.png
-rw-r--r--  1 motin  staff      959 Feb 27 14:13 [sing.player5]lyric_active.png
-rw-r--r--  1 motin  staff      877 Feb 27 14:13 [sing.player5]lyric_inactive.png
-rw-r--r--  1 motin  staff      960 Feb 27 14:13 [sing.player6]lyric_active.png
-rw-r--r--  1 motin  staff      872 Feb 27 14:13 [sing.player6]lyric_inactive.png
-rw-r--r--  1 motin  staff      360 Feb 27 14:13 [sing]LyricsBall.png
-rw-r--r--  1 motin  staff      973 Feb 27 14:13 [sing]SongName.png
-rw-r--r--  1 motin  staff     1344 Feb 27 14:13 [sing]lineBonusPopUp.png
-rw-r--r--  1 motin  staff     3061 Feb 27 14:13 [sing]lyricsHelpBar.png
-rw-r--r--  1 motin  staff      292 Feb 27 14:13 [sing]notesBgLeft.png
-rw-r--r--  1 motin  staff      144 Feb 27 14:13 [sing]notesBgMid.png
-rw-r--r--  1 motin  staff      280 Feb 27 14:13 [sing]notesBgRight.png
-rw-r--r--  1 motin  staff      671 Feb 27 14:13 [sing]notesLeft.png
-rw-r--r--  1 motin  staff      236 Feb 27 14:13 [sing]notesMid.png
-rw-r--r--  1 motin  staff      681 Feb 27 14:13 [sing]notesPlainLeft.png
-rw-r--r--  1 motin  staff      151 Feb 27 14:13 [sing]notesPlainMid.png
-rw-r--r--  1 motin  staff      690 Feb 27 14:13 [sing]notesPlainRight.png
-rw-r--r--  1 motin  staff      728 Feb 27 14:13 [sing]notesRight.png
-rw-r--r--  1 motin  staff      637 Feb 27 14:13 [sing]p.png
-rw-r--r--  1 motin  staff    15290 Feb 27 14:13 [sing]pause.png
-rw-r--r--  1 motin  staff      261 Feb 27 14:13 [sing]scoreBg.png
-rw-r--r--  1 motin  staff      203 Feb 27 14:13 [sing]singBarBack.png
-rw-r--r--  1 motin  staff      371 Feb 27 14:13 [sing]singBarBar.jpg
-rw-r--r--  1 motin  staff      183 Feb 27 14:13 [sing]singBarBar.png
-rw-r--r--  1 motin  staff      199 Feb 27 14:13 [sing]singBarFront.png
-rw-r--r--  1 motin  staff     4706 Feb 27 14:13 [sing]textBar.png
-rw-r--r--  1 motin  staff     7448 Feb 27 14:13 [sing]textBarDuet.png
-rw-r--r--  1 motin  staff      317 Feb 27 14:13 [sing]timeBar.jpg
-rw-r--r--  1 motin  staff      286 Feb 27 14:13 [sing]timeBarBG.png
-rw-r--r--  1 motin  staff     2959 Feb 27 14:13 [song]duetsinger.png
-rw-r--r--  1 motin  staff     2959 Feb 27 14:13 [song]duetsinger2.png
-rw-r--r--  1 motin  staff     3026 Feb 27 14:13 [song]duetsinger3.png
-rw-r--r--  1 motin  staff     3223 Feb 27 14:13 [song]message.png
-rw-r--r--  1 motin  staff      229 Feb 27 14:13 [special]bar1.png
-rw-r--r--  1 motin  staff      410 Feb 27 14:13 [special]bar2.png
-rw-r--r--  1 motin  staff    32518 Feb 27 14:13 [special]bg_fade.png
-rw-r--r--  1 motin  staff      388 Feb 27 14:13 [stat]detailBG1.png
-rw-r--r--  1 motin  staff      378 Feb 27 14:13 [stat]mainBG1.png
-rw-r--r--  1 motin  staff    12014 Feb 27 14:13 [stat]mainBG2.png
-rw-r--r--  1 motin  staff      300 Feb 27 14:13 [stat]mainBG3.png
-rw-r--r--  1 motin  staff    44063 Feb 27 14:13 [tournament]trophy.png
-rw-r--r--  1 motin  staff     6967 Feb 27 14:13 [tournament]winner.png
```

**Comment by basisbit** [comment] 2017-02-27 15:47
the files exist and are readable, but could not be loaded. We will have to add some more debugging output, send you the modified version and then ask you upload another Error.log. My guess would be that there is some filename Encoding bug.

**Comment by motin** [comment] 2017-03-01 13:21
Looking forward to try the debug-build. 
Btw, it was on that computer that I tried to follow the OSX compile instructions previously (failed).

**Comment by dlb21** [comment] 2017-03-01 13:30
Same problem on my iMac with Sierra 10.12.3

**Comment by arte1337** [comment] 2017-03-08 18:53
same issue of my new mac with sierra

**Comment by ePirat** [comment] 2017-03-12 23:44
Please try the following build: https://transfer.sh/PI7t1/ultrastardeluxe-e4c0826.dmg

It hopefully adds some info to the logs what is failing.
You can find the log at

```
~/Library/Logs/UltraStar\ Deluxe/Error.log
```

Please do not paste it into the comment but for example to gist.github.com and post only the link to it here. Thanks in advance!

**Comment by arte1337** [comment] 2017-03-13 15:48
@ePirat  

https://gist.github.com/anonymous/a3a2778f3c47afd65b3d270f747b875a

**Comment by ePirat** [comment] 2017-03-13 16:05
Thanks!

```
ERROR:  Could not load image "[…]/UltraStarDeluxe1.3/resources/icons/ultrastardx-icon.png", Error: Failed loading libpng.dylib: dlopen(libpng.dylib, 6): image not found [LoadImage]
```

That's what I was looking for.

**Comment by arte1337** [comment] 2017-03-13 16:07
@ePirat No problem... I knew what you were searching for, but I just sent the whole error log.

Good luck with fixing it. Thank you!

**Comment by ePirat** [comment] 2017-03-13 16:16
Steps to reproduce on systems where libraries in question were installed by homebrew:

Start USDX like the following:

```
DYLD_FALLBACK_LIBRARY_PATH="" ./UltraStarDeluxe.app/Contents/MacOS/ultrastardx
```

from Terminal.

**Comment by arte1337** [comment] 2017-03-13 16:55
@ePirat It's not doing anything. What do you need to know?

**Comment by ePirat** [comment] 2017-03-13 17:25
This was just a hint for myself/other macOS developers (if any) which are unable to reproduce the Problem. Currently nothing I need you to do.

Fixing this shouldn't be that hard, I might have a new build to test in the next days. Thanks a lot for all the reports.

**Comment by jaimevisser** [comment] 2017-04-12 16:30
Reproducible on a MBPr running el capitan. Maybe you can share the missing lib so we can run ultrastar?

**Comment by ePirat** [comment] 2017-04-12 18:18
The problem is not that the library is missing, the problem is that SDL won't find it. I might have some time tomorrow or later today to look into this and provide a fix.

**Comment by ePirat** [comment] 2017-04-13 22:45
It seems that we need to build SDL2 with `--disable-sdl-dlopen` to prevent it using dlopen.

**Comment by ePirat** [comment] 2017-04-13 22:55
@jaimevisser 

> Installing brew and libs fixed this.

Thats just a workaround though.

**Comment by MalcolmSmithUK** [comment] 2017-07-22 13:40
Reproduced on MacBook Air El Capitan.

**Comment by loshal** [comment] 2017-08-02 06:10
@jaimevisser
Which libs should I install with brew to make it work? I tried SDL2, with no success. (I'm running MacOS Sierra on a MacBook Air.)

**Comment by kamilsarelo** [comment] 2017-08-04 17:23
Bug still reproducible on macOS Sierra 10.12.6.
Any hint on the brew libs required to workaround this ?

**Comment by kamilsarelo** [comment] 2017-08-04 18:24
Bug still reproducible on macOS Sierra 10.12.6.
Any hint on the brew libs required to workaround this ?

**Comment by kamilsarelo** [comment] 2017-08-04 18:25
...just installed the libs mentioned here:
https://github.com/UltraStar-Deluxe/USDX/wiki/Compiling-UltraStar-Deluxe
...via brew and everything works fine again !

**Comment by loshal** [comment] 2017-08-05 07:14
It tried installing only these two libraries with brew and it works:
libpng
libtiff

**Comment by bole5** [comment] 2017-10-17 14:14
I was able to get the version **UltraStar.Deluxe_v2017.8.0.stable.dmg** to work fine with the graphics on Sierra 10.12.6 by installing **libpng**.
brew install libpng

This was done on a non-development (clean) Mac OSX Sierra machine. Can you statically link libpng?

**Comment by ePirat** [comment] 2017-10-17 16:26
Yes, I am already aware of that, thanks anyway!

> It seems that we need to build SDL2 with --disable-sdl-dlopen to prevent it using dlopen.

**Comment by ePirat** [comment] 2017-10-17 16:30
We already include libpng in the app bundle, the problem is that SDL2 tries to use `dlopen` which does not find the dylib in the app bundle.

**Comment by s09bQ5** [comment] 2017-10-18 13:13
How about something like chdir(@executable_path) when usdx starts?
Do we change the working directory afterwards?

**Comment by ePirat** [comment] 2017-10-18 14:19
I think I already have a solution for this, I just had no time so far to try if it works.

**Comment by s09bQ5** [comment] 2017-10-23 14:06
From the short discussion on IRC:
- There are more libraries loaded with dlopen (pcre, opencv)
- We will try to chdir() to the directory returned by _NSGetExecutablePath()

**Comment by ePirat** [comment] 2018-01-21 09:58
Please try this build: https://github.com/ePirat/USDX/releases/download/1.3.6/UltraStarDeluxe-1.3.6.zip
This should hopefully fix the problem.

**Comment by tobihagemann** [comment] 2018-08-25 08:05
@ePirat Just wanted to say that your build fixed the problem. Stumbled upon this issue while trying to get UltraStarDeluxe running on Mojave. I'm glad I found your solution (even though installing some libraries via brew would've probably worked as well as a workaround). Thanks!

**Comment by ePirat** [comment] 2018-08-25 08:49
@tobihagemann Thanks for confirming that my build fixes it.

**Comment by bohning** [comment] 2023-08-27 11:42
I think this can be closed.

**Comment by barbeque-squared** [comment] 2023-08-27 17:07
Was this ever addressed? Regardless, I'm pretty sure it works with fine in the current versions, so yeah, makes sense to close it.

**Closed by barbeque-squared** 2023-08-27 17:07 UTC
Labels: bug, macOS

**Comment by s09bQ5** [comment] 2023-08-27 17:43
From what @ePirat wrote in 2017 the correct fix nowadays IMHO is to configure the sdl2_image build with `--disable-jpg-shared --disable-png-shared --disable-webp-shared --disable-tif-shared`. We stopped using PCRE in November 2017 and current versions of OpenCV are not loaded with dlopen.
