### ISSUE TITLE
Delay between voice entering the microphone and voice exiting the speakers.

### ISSUE THREAD

**Issue by tretos53** [UltraStar-Deluxe/USDX#518] opened 2020-04-27 15:16 UTC
### Actual behaviour

When `Microphone Playback` is set to `On` there is a significant delay between my voice entering the microphone and my voice exiting the speakers.

When testing Microphone in Windows control panel with `listening to this device` option se to on there is no delay.

This doesn't seem to affect the singing score and the voice is correctly recognised.

### Expected behaviour

There should be no delay.

### Steps to reproduce

1. Open the ultrastardx.exe
2. Go to Options / Sound and make sure the Microphone Playback is set to On
3. Go to the main screen and click `Sing`
4. Select a player, a song and start singing.

### Details

Provide some additional information:

- USDX version: UltraStar.Deluxe_v2017.8.0.stable_installer.exe
- Operating System + version: Windows 10 Pro v.1903 b.18362.778

**Comment by basisbit** [comment] 2020-04-27 15:47
Thank you for this problem report. Unfortunately, this is a known limitation and we do not plan on changing this anytime soon. Please instead use your audio device settings to make the hardware directly play back input from the microphone. 

In windows, open sound settings, click on Sound-Systemcontrol, then Recording, Listen, Use this Device as audio source for playback (or similar translations, see screenshot):
![image](https://user-images.githubusercontent.com/10870269/80391983-d0621f80-88ae-11ea-9efd-040c5cd5cba7.png)

Duplicate of #506

**Closed by basisbit** 2020-04-27 15:47 UTC

**Comment by complexlogic** [comment] 2022-03-26 01:51
Since the workaround given by @basisbit is specific to Windows, I created a script which will do the same thing in Linux via PulseAudio. It is available [here](https://github.com/complexlogic/ultrastar-playback) for anybody that is interested.
