### ISSUE TITLE
[BUG] USDX crashes if the song path is too long (Win, not Mac)

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#184] opened 2016-12-09 07:14 UTC
USDX crashes with too long path/file names. However, I noticed this problem with the Windows version, not with the Mac version. The path contains 164 characters according to the text editor.
![pfadzulang](https://cloud.githubusercontent.com/assets/1497707/21026137/9c13a858-bd8b-11e6-84cc-390682e779ce.jpg)

On my Mac, starting USDX with the same path doesn't lead to problems, the song is loaded without problems:
<img width="1680" alt="bildschirmfoto 2016-12-08 um 21 13 50" src="https://cloud.githubusercontent.com/assets/1497707/21026203/e0f90e7c-bd8b-11e6-895b-58398995c388.png">

As a first step, it would be great if USDX could at least ignore the song, add an entry to the error.log and continue instead of crashing, if somehow possible. It was tedious to find out which song was causing this (not knowing that it was the path length that caused it).

**Comment by RattleSN4K3** [comment] 2016-12-09 14:22
A _path_ is the full path including filename, extension and path/folder. If your file is the same as the folder, the full path will reach more than 260 chars.
```
G:\00:Karaoke\!newSongs\!cleaned_nonforeign\!to_integrate\J\Jennifer Rostock feat. Madsen, MC Fitti, Großstadtgeflüster & Feine Sahne Fischfilet - K.b.a.g. [VIDEO]\Jennifer Rostock feat. Madsen, MC Fitti, Großstadtgeflüster & Feine Sahne Fischfilet - K.b.a.g. [VIDEO].txt
```

The MAX_PATH problem on latest Windows version can be solved by using the Unicode prefix `\\?\`. I once tried implementing it, but it failed when saving files and created an _empty file_.

**Comment by bohning** [comment] 2016-12-09 22:13
@RattleSN4K3: Yes, the file is the same as the folder, so the full path exceeds the 255 characters limit, I assume. Of course, it would not be a problem to shorten this particular path/filename, but since USDX crashes, it is difficult to find out which song is exactly causing the crash (I was bisecting my song collection until I finally singled out the problematic song, not knowing that the long path name was the problem in the first place.)

**Comment by RattleSN4K3** [comment] 2016-12-11 18:19
Long filenames/paths is not a USDX problem per se. It's generally the OS (in this case Windows writing files to a NTFS partition).

You should also not be able to rename the file `Jennifer Rostock feat. Madsen, MC Fitti, Großstadtgeflüster & Feine Sahne Fischfilet - K.b.a.g. [VIDEO].txt` (or what ever the file as exactly called) from the _Windows Explorer_ resulting in path exceeding the 260 chararacters length. For instance in:  
`Jennifer Rostock feat. Madsen, MC Fitti, Großstadtgeflüster & Feine Sahne Fischfilet - K.b.a.g. [VIDEO] - Copy.txt`

Some times even copying folders with sub-folders or files exceeding the length can be a problem. In general when using multiple operation systems simultaneously, try to avoid such hardlinks/files with a deep folder structure.

But nonetheless, USDX should either try to work around that problem (using `\\?\`) or completely ignore such files (and likely inform in a messagebox and/or error log) instead of simply crashing. Let's see what works best without risking anyone losing data.

On Windows 10, you can actually disable the limitation:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath

PS: You can use tools to check for such files. An open-source one:  
https://pathlengthchecker.codeplex.com/

**Comment by basisbit** [comment] 2016-12-22 14:52
duplicate of #41

**Closed by basisbit** 2016-12-22 14:52 UTC
Labels: duplicate
