### ISSUE TITLE
Does not launch on mac 10.12

### ISSUE THREAD

**Issue by MindaugasJ** [UltraStar-Deluxe/USDX#204] opened 2016-12-27 20:36 UTC
Hi, i have this problem since 10.10 mac

It launches as in icon appears in dock, but game itself doe snot launch. Is there a fix?

**Comment by basisbit** [comment] 2016-12-27 21:04
please provide more details. What version did you try to run and how did you compile/install it? What do you see when launching from terminal?

**Comment by motin** [comment] 2017-01-02 08:59
Running OSX 10.11 here. 
Same issue when trying to launch version 1.1 Final on OSX. 

The windows-version of the latest 1.3-beta runs on OSX 10.11 using [Wineskin](http://wineskin.urgesoftware.com/tiki-index.php).

Tried compiling the latest 1.3 beta on OSX using the instructions on https://github.com/UltraStar-Deluxe/USDX#compiling-on-os-x but got too many "Package * was not found in the pkg-config search path"-issues so i gave up for now.

**Comment by ePirat** [comment] 2017-01-27 01:59
I ran into the same issues with the latest stable version from the Website (v1.1 Final), but this seems fixed in the v1.3.5-beta, as I downloaded the source and compiled it on my Mac (running macOS 10.12), and it is working fine.

**Comment by darkgaze** [comment] 2017-02-10 14:45
Posible duplicate?  Does it execute the first time?   Sadly I have no time to compile the new version. Is it available somewhere?
https://github.com/UltraStar-Deluxe/USDX/issues/223

**Comment by ePirat** [comment] 2017-02-26 14:03
Please try the following build: https://yaycdn.de/builds/osx/usdx/usdx_1_3_5_2017-02-15.dmg

**Comment by motin** [comment] 2017-02-27 10:59
@ePirat Yay, that build launches fine :) Would be great if the build is added to the website so that mac users can try the latest beta version.

**Comment by basisbit** [comment] 2017-02-27 11:42
closing this issue because the problems reported initially by this issue are fixed and confirmed.

**Closed by basisbit** 2017-02-27 11:42 UTC
Labels: invalid

**Comment by basisbit** [comment] 2017-02-27 11:44
will add a current build to the [usdx.eu](https://usdx.eu/) website
