### ISSUE TITLE
Raspberry FPC error

### ISSUE THREAD

**Issue by amerinoj** [UltraStar-Deluxe/USDX#598] opened 2022-01-02 23:29 UTC
Hi, I will share my experience with a common error in raspbian so.

Let's go.

When you try compile the current  UDX version in "Raspbian GNU/Linux 10 (buster)" the FPC show the next error:
"
checking version of fpc... [Error: ppcarm can't be executed, error message: Failed to execute "ppcarm", error code: 127]
"

To resolve it , check the missing or breaking  fpc link , and if is necessary create a new symbolic link.
if you execute in rapbian the next command "fpc -iV " and return the next error :
"
 [Error: ppcarm can't be executed, error message: Failed to execute "ppcarm", error code: 127]
"

move the fpc link and ppcarm link 

"
cd /usr/bin
sudo rm fpc fpc_old 
sudo rm ppcarm ppcarm_old 
ls -la /usr/bin/*_old
lrwxrwxrwx 1 root root 21 ene  2 21:43 /usr/bin/fpc_old -> /etc/alternatives/fpc
lrwxrwxrwx 1 root root 31 ene  2 22:30 /usr/bin/ppcarm_old -> /usr/local/lib/fpc/3.2.2/ppcarm
"
Create the new links 
" ​cd /usr/bin/
sudo ln -s ppcarm-3.0.4 ppcarm 
sudo ln -s ppcarm fpc

"
And check 
"
pi@raspberrypi:/usr/bin $ ls -la fpc
lrwxrwxrwx 1 root root 6 ene  3 00:00 fpc -> ppcarm
pi@raspberrypi:/usr/bin $ ls -la ppcarm
lrwxrwxrwx 1 root root 12 ene  2 23:57 ppcarm -> ppcarm-3.0.4
pi@raspberrypi:/usr/bin $ ls -la ppcarm-3.0.4 
lrwxrwxrwx 1 root root 43 feb  4  2019 ppcarm-3.0.4 -> ../lib/arm-linux-gnueabihf/fpc/3.0.4/ppcarm

"
now try to compile to execute again the configuration ./configure and compile

Regards.

**Comment by s09bQ5** [comment] 2022-01-03 02:08
This is not a bug in USDX and to me it looks like you manually installed the FPC 3.2.2 tarball over the FPC 3.0.4 deb package installed with Raspbian (because 3.2.2 lived in /usr/local).

Github issues are a bad place to share knowledge because issues are closed as soon as possible and are then hidden from normal searches.

**Comment by amerinoj** [comment] 2022-01-03 09:23
Hi, I install FPC from the Raspbian repositories as appear in the README.

I know that Github issues is a good place to do this, but if you  want can add a comment in the README file under a Raspbian instalation seccion .

**Comment by basisbit** [comment] 2022-01-03 15:50
Closing this because it is not a bug in USDX. Please ask in a Raspbian forum or in a FPC forum for how to get your freepascal setup working again.

On a side note, USDX on raspbian is quite slow, you might want to instead take a look at Performous, which works nicely on RaspberryPi, even on the older models.

**Closed by basisbit** 2022-01-03 15:50 UTC
